name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}

    - name: Login to DO Registry
      run: doctl registry login

    - name: Build Docker Image
      run: docker build -t registry.digitalocean.com/demo-cicd/cicd-demo:latest .

    - name: Push Image
      run: docker push registry.digitalocean.com/demo-cicd/cicd-demo:latest

    - name: Deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull registry.digitalocean.com/demo-cicd/cicd-demo:latest
          docker stop app || true
          docker rm app || true
          docker run -d -p 80:5000 --name app registry.digitalocean.com/demo-cicd/cicd-demo:latest
